In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
aria     = pd.read_csv("/home/stu14/s16/acm7552/Capstone/results/AEROBLADE_outputs/aria_detection_results.csv")
artbench = pd.read_csv("/home/stu14/s16/acm7552/Capstone/results/AEROBLADE_outputs/artbench_detection_results.csv")

In [4]:
aria

,Unnamed: 0,fake_dir,transform,repo_id,distance_metric,acc,ap,auc,tpr5fpr
0,0,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_0,0.480469,0.316168,0.058960,0.000000
1,16,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_1,0.480469,0.313649,0.050171,0.000000
2,32,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_2,0.480469,0.310503,0.018860,0.000000
3,48,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_3,0.480469,0.311195,0.019897,0.000000
4,64,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_4,0.480469,0.329835,0.131866,0.000000
...,...,...,...,...,...,...,...,...,...
187,123,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,max,lpips_vgg_1,0.488281,0.414422,0.384674,0.015625
188,139,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,max,lpips_vgg_2,0.480469,0.410860,0.400208,0.000000
189,155,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,max,lpips_vgg_3,0.480469,0.437267,0.465973,0.000000
190,171,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,max,lpips_vgg_4,0.480469,0.488237,0.555786,0.000000
191,187,/home/stu14/s16/acm7552/Capstone/data/ARIA_dat...,clean,max,lpips_vgg_5,0.480469,0.505051,0.569977,0.015625

In [5]:
artbench

,Unnamed: 0,fake_dir,transform,repo_id,distance_metric,acc,ap,auc,tpr5fpr
0,0,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_0,0.480469,0.477650,0.526978,0.0
1,20,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_1,0.480469,0.424472,0.411652,0.0
2,40,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_2,0.480469,0.471229,0.493469,0.0
3,60,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_3,0.480469,0.478778,0.529388,0.0
4,80,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,CompVis/stable-diffusion-v1-1,lpips_vgg_4,0.480469,0.473020,0.531647,0.0
...,...,...,...,...,...,...,...,...,...
235,157,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,max,lpips_vgg_1,0.480469,0.320717,0.090302,0.0
236,177,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,max,lpips_vgg_2,0.480469,0.309876,0.006805,0.0
237,197,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,max,lpips_vgg_3,0.480469,0.343826,0.187592,0.0
238,217,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,max,lpips_vgg_4,0.480469,0.444487,0.469330,0.0
239,237,/home/stu14/s16/acm7552/Capstone/data/Real_AI_...,clean,max,lpips_vgg_5,0.480469,0.453876,0.483673,0.0

In [7]:
print(aria["acc"].mean())
print(aria["ap"].mean())
print(aria["auc"].mean())
print()



print(artbench["acc"].mean())
print(artbench["ap"].mean())
print(artbench["auc"].mean())

0.4864501953125
0.4036658316964961
0.3116620381673177

0.48138020833333334
0.40635157586966814
0.30966517130533855